### ISSUE TITLE
no rainbow within javascript code blocks

### ISSUE THREAD

**Issue by stumash** [frazrepo/vim-rainbow#8]
![image](https://user-images.githubusercontent.com/13181078/93320727-6a375400-f7df-11ea-9fb0-e458110c7b3c.png)

I suspect foul play with other plugins. Any tips on how to resolve problems like these?

**Comment by ghost** [comment]
I can confirm this behaviour, using NVIM v0.5.0-692-gc7ef80220 on Arch Linux.

**Comment by stumash** [comment]
I've identified the source to be the [vim-javascript](https://github.com/pangloss/vim-javascript) plugin, which is imported by the [vim-polyglot](https://github.com/sheerun/vim-polyglot) plugin.

Looking into a fix

**Comment by stumash** [comment]
this issue was discussed on the vim-javascript issue board at length [here](https://github.com/pangloss/vim-javascript/issues/85) and [here](https://github.com/pangloss/vim-javascript/issues/184). There is no known fix 😢
